### ISSUE TITLE
I still get 130% CPU usage after 20 hours of uptime

### ISSUE THREAD

**Issue by crazyyi** [tangmi/node-gameloop#4]
For the first few hours I can play without any problem. But then the game become very slow. CPU usage is up to 130%. Any idea what is wrong with the code? I think using `setImmediate(gameloop)` is the culprit.

**Comment by Jared-Sprague** [comment]
I was also getting over 100% CPU on my game server with no clients connected immediately after starting the server.  I traced this down using the built in node profiler to figure out that node-gameloop was the culprit.

After downgrading to 0.1.0,  the problem went away and CPU levels went back to normal.  I definitely think this is a major bug in this node-gameloop and makes the current version unusable in production environments.

Below is my CPU prorofile,  looks like it might be the use of `node::Hrtime`
```
 [C++]:
   ticks  total  nonlib   name
   4579    9.2%   11.2%  node::Hrtime(v8::FunctionCallbackInfo<v8::Value> const&)

...

   4579    9.2%  node::Hrtime(v8::FunctionCallbackInfo<v8::Value> const&)
   4579  100.0%    /usr/bin/node
   4579  100.0%      LazyCompile: *gameLoop /usr/share/games/zorbio/node_modules/node-gameloop/lib/gameloop.js:54:27
   4576   99.9%        LazyCompile: *runCallback timers.js:666:21
   4576  100.0%          LazyCompile: tryOnImmediate timers.js:641:24
   4576  100.0%            LazyCompile: *processImmediate timers.js:592:26


```

**Comment by Jared-Sprague** [comment]
After doing some more research I tracked down the CPU degredation to 0.1.3.

See before and after screen shots:
## 0.1.2
![screenshot from 2017-11-20 11-30-05](https://user-images.githubusercontent.com/3926730/33029284-2d4fd9e8-cde6-11e7-86bb-a3c16aa98ddc.png)

## 0.1.3
![screenshot from 2017-11-20 11-28-51](https://user-images.githubusercontent.com/3926730/33029219-068c1e8e-cde6-11e7-9fb9-8b211c3f4463.png)

**Comment by Jared-Sprague** [comment]
tracked down the exact line that is causing the CPU issue the `process.hrtime()` call here:
https://github.com/tangmi/node-gameloop/commit/f10cd69caa898c4834eb49627d14bc300d1bcb5b

This is confirmed by my CPU profiling above.

**Comment by crazyyi** [comment]
@Jared-Sprague Hi I am going to close this issue as this is my fault. I had some memory leak in my game logic code. Now it is fixed. The problem is not related to this module. Your problem looks a bit different than mine. Feel free to create a new issue if you like.
